/**
 * A master written by the pipeline that used to run in a container.
 *
 * `fixtures/python-docx-master.docx` was generated by
 * `services/converter/app/docx/builder.py` — python-docx, the builder
 * this one replaced — before that service was deleted on 2026-08-26.
 *
 * It is committed because the masters already sitting in R2 were written
 * by exactly that code, and the reader has to keep reading them. Nothing
 * else guards that property any more: the implementation that produced
 * these bytes is gone, so this file is the only remaining evidence of
 * what it produced. Do not regenerate it from the current builder — that
 * would make the test agree with itself and prove nothing.
 */

import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'

import { readDocx } from './docxRead'

const LEGACY = new Uint8Array(
  readFileSync(fileURLToPath(new URL('./fixtures/python-docx-master.docx', import.meta.url))),
)

describe('a master from the retired Python builder', () => {
  const doc = readDocx(LEGACY, 'fallback')

  it('still carries its metadata', () => {
    expect(doc.title).toBe('參禪日記')
    expect(doc.author).toBe('南懷瑾')
  })

  it('still resolves every block kind', () => {
    expect(doc.blocks.map((b) => b.kind)).toEqual([
      'chapter',
      'body',
      'section',
      'marker',
      'verse',
      'attribution',
      'footnote',
      'chapter',
      'body',
    ])
  })

  it("still keeps a poem's own line breaks", () => {
    expect(doc.blocks.find((b) => b.kind === 'verse')?.lines).toEqual([
      '空山不見人',
      '但聞人語響',
    ])
  })

  it('still re-attaches the source reference', () => {
    expect(doc.blocks.find((b) => b.kind === 'attribution')?.sourceRef).toBe('（見第 71 頁）')
  })

  it('does not mistake the page-break paragraphs for empty body blocks', () => {
    // python-docx wrote a bare `Normal` paragraph before each chapter to
    // carry the page break. Reading those as blocks would put an empty
    // paragraph into the EPUB at every chapter opening.
    expect(doc.blocks.every((b) => b.lines.some((line) => line.trim()))).toBe(true)
  })
})
