<?php
/**
 * Seed content importer, run via `wp eval-file` (full WP bootstrap
 * available). Creates real public-domain books so the catalog -> book ->
 * download flow can be exercised end to end out of the box.
 *
 * Data-driven: add an entry to $books below and re-run. Idempotent per
 * book (matched on slug), so `docker compose up` never duplicates
 * content and new books can be added to an already-seeded site.
 *
 * The files themselves are generated by tools/generate-seed-content.py.
 */

if (!defined('ABSPATH')) {
    exit;
}

$seed_root = WP_PLUGIN_DIR . '/nobleread-core/seed-content/';

/** Download-format key => Part meta key. */
$format_meta = [
    'docx' => 'nr_docx_attachment_id',
    'epub' => 'nr_epub_attachment_id',
    'pdf_standard' => 'nr_pdf_standard_attachment_id',
    'pdf_large' => 'nr_pdf_large_attachment_id',
    'pdf_xl' => 'nr_pdf_xl_attachment_id',
];

$books = [
    [
        'slug' => 'tao-te-ching',
        'title' => 'Tao Te Ching (道德经)',
        'author' => 'Laozi (老子)',
        'translator' => 'James Legge (1891)',
        'language' => 'Chinese / English',
        'rights' => 'public_domain',
        'dir' => 'tao-te-ching-ch1',
        'cover' => 'cover.jpg',
        'description' => "One of the foundational texts of Chinese philosophy, traditionally attributed to Laozi. This edition presents James Legge's 1891 translation (public domain) alongside the original Chinese text.",
        'parts' => [
            [
                'title' => 'Chapter 1 / 第一章',
                'files' => [
                    'docx' => 'master.docx',
                    'epub' => 'part-1.epub',
                    'pdf_standard' => 'part-1-pdf-standard.pdf',
                    'pdf_large' => 'part-1-pdf-large.pdf',
                    'pdf_xl' => 'part-1-pdf-xl.pdf',
                ],
            ],
        ],
    ],
    [
        'slug' => 'analects',
        'title' => 'The Analects (論語)',
        'author' => 'Confucius (孔子)',
        'translator' => 'James Legge (1893)',
        'language' => 'Chinese / English',
        'rights' => 'public_domain',
        'dir' => 'analects',
        'cover' => 'cover.jpg',
        'description' => "The recorded sayings of Confucius and his disciples, compiled by later followers — among the most influential works in Chinese thought on learning, character, and how to live well. This edition presents James Legge's 1893 translation (public domain) alongside the original Chinese.",
        'parts' => [
            ['title' => 'Book I — 學而 (Xue Er)', 'dir' => 'book-1'],
            ['title' => 'Book II — 為政 (Wei Zheng)', 'dir' => 'book-2'],
            ['title' => 'Book III — 八佾 (Ba Yi)', 'dir' => 'book-3'],
        ],
    ],
];

/** Default per-part filenames when a part lives in its own directory. */
$default_part_files = [
    'docx' => 'master.docx',
    'epub' => 'part.epub',
    'pdf_standard' => 'pdf-standard.pdf',
    'pdf_large' => 'pdf-large.pdf',
    'pdf_xl' => 'pdf-xl.pdf',
];

/**
 * Import a local file into the media library under an explicit name and
 * return its attachment ID, or 0 if the source is missing. The explicit
 * name keeps parts distinguishable in the media library, since several
 * of them share a source filename.
 */
function nr_seed_import_file($path, $filename) {
    if (!file_exists($path)) {
        WP_CLI::warning("Seed file missing: {$path}");
        return 0;
    }

    $upload = wp_upload_bits($filename, null, file_get_contents($path));
    if (!empty($upload['error'])) {
        WP_CLI::warning("Upload failed for {$filename}: " . $upload['error']);
        return 0;
    }

    $filetype = wp_check_filetype($filename, null);
    $attachment_id = wp_insert_attachment(
        [
            'post_mime_type' => $filetype['type'],
            'post_title' => sanitize_file_name($filename),
            'post_content' => '',
            'post_status' => 'inherit',
        ],
        $upload['file']
    );

    require_once ABSPATH . 'wp-admin/includes/image.php';
    wp_update_attachment_metadata(
        $attachment_id,
        wp_generate_attachment_metadata($attachment_id, $upload['file'])
    );

    return $attachment_id;
}

$created = 0;

foreach ($books as $book) {
    $existing = get_posts([
        'post_type' => 'nr_book',
        'name' => $book['slug'],
        'post_status' => 'any',
        'numberposts' => 1,
    ]);

    if (!empty($existing)) {
        WP_CLI::log("Book '{$book['slug']}' already exists (#{$existing[0]->ID}) — skipping.");
        continue;
    }

    WP_CLI::log("Creating book: {$book['title']}");

    $book_id = wp_insert_post([
        'post_type' => 'nr_book',
        'post_title' => $book['title'],
        'post_name' => $book['slug'],
        'post_status' => 'publish',
        'post_content' => $book['description'],
    ], true);

    if (is_wp_error($book_id)) {
        WP_CLI::warning("Failed to create '{$book['slug']}': " . $book_id->get_error_message());
        continue;
    }

    update_post_meta($book_id, 'nr_author', $book['author']);
    update_post_meta($book_id, 'nr_translator', $book['translator']);
    update_post_meta($book_id, 'nr_language', $book['language']);
    update_post_meta($book_id, 'nr_rights_status', $book['rights']);

    $book_dir = $seed_root . $book['dir'] . '/';

    if (!empty($book['cover'])) {
        $cover_id = nr_seed_import_file(
            $book_dir . $book['cover'],
            $book['slug'] . '-cover.jpg'
        );
        if ($cover_id) {
            set_post_thumbnail($book_id, $cover_id);
        }
    }

    foreach ($book['parts'] as $index => $part) {
        $part_id = wp_insert_post([
            'post_type' => 'nr_part',
            'post_title' => $part['title'],
            'post_status' => 'publish',
            'post_parent' => $book_id,
            'menu_order' => $index + 1,
        ], true);

        if (is_wp_error($part_id)) {
            WP_CLI::warning("Failed to create part '{$part['title']}': " . $part_id->get_error_message());
            continue;
        }

        $part_dir = isset($part['dir']) ? $book_dir . $part['dir'] . '/' : $book_dir;
        $files = isset($part['files']) ? $part['files'] : $default_part_files;
        $prefix = $book['slug'] . '-' . (isset($part['dir']) ? $part['dir'] : 'part-' . ($index + 1));

        foreach ($format_meta as $format => $meta_key) {
            if (empty($files[$format])) {
                continue;
            }
            $source = $part_dir . $files[$format];
            $target = $prefix . '-' . $files[$format];
            update_post_meta($part_id, $meta_key, nr_seed_import_file($source, $target));
        }

        WP_CLI::log("  + part #{$part_id}: {$part['title']}");
    }

    update_post_meta($book_id, '_nr_seed_version', '2');
    $created++;
}

WP_CLI::success($created ? "Seeded {$created} book(s)." : 'All seed books already present.');
